name: prayu_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  flutter_dotenv: ^5.2.1
  onesignal_flutter: ^5.2.8
  flutter_native_splash: ^2.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"
flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/prayu_logo_1024.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#CECFFF"
  image: assets/icon/prayu_logo_text.png
  android: true
  ios: true
  fullscreen: true
