name: prayu_app
description: "A new Flutter project."
publish_to: "none"
version: 1.2.2+17
environment:
  sdk: "3.5.4"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.8"
  flutter_inappwebview: "6.1.5"
  flutter_dotenv: "5.2.1"
  onesignal_flutter: "5.2.8"
  flutter_native_splash: "2.4.3"
  url_launcher: "6.3.1"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"
flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.staging
    - .env.prod

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/prayu_logo_1024.png"
  adaptive_icon_foreground: "assets/icon/prayu_logo_1024.png"
  adaptive_icon_background: "#CECFFF"
  min_sdk_android: 21

flutter_native_splash:
  color: "#CECFFF"
  image: assets/icon/prayu_logo_text.png
  android: true
  ios: true
  fullscreen: true
